// Generated by jextract

package com.loadingbyte.cinecred.natives.clippercapi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class clippercapi_h extends clippercapi_h$shared {

    clippercapi_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int true_ = (int)1L;
    /**
     * {@snippet lang=c :
     * #define true 1
     * }
     */
    public static int true_() {
        return true_;
    }
    private static final int false_ = (int)0L;
    /**
     * {@snippet lang=c :
     * #define false 0
     * }
     */
    public static int false_() {
        return false_;
    }
    private static final int __bool_true_false_are_defined = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __bool_true_false_are_defined 1
     * }
     */
    public static int __bool_true_false_are_defined() {
        return __bool_true_false_are_defined;
    }

    private static class ClipType_NoClip {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ClipType_NoClip");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int ClipType_NoClip()
     * }
     */
    public static FunctionDescriptor ClipType_NoClip$descriptor() {
        return ClipType_NoClip.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int ClipType_NoClip()
     * }
     */
    public static MethodHandle ClipType_NoClip$handle() {
        return ClipType_NoClip.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int ClipType_NoClip()
     * }
     */
    public static MemorySegment ClipType_NoClip$address() {
        return ClipType_NoClip.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int ClipType_NoClip()
     * }
     */
    public static int ClipType_NoClip() {
        var mh$ = ClipType_NoClip.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ClipType_NoClip");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ClipType_Intersection {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ClipType_Intersection");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int ClipType_Intersection()
     * }
     */
    public static FunctionDescriptor ClipType_Intersection$descriptor() {
        return ClipType_Intersection.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int ClipType_Intersection()
     * }
     */
    public static MethodHandle ClipType_Intersection$handle() {
        return ClipType_Intersection.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int ClipType_Intersection()
     * }
     */
    public static MemorySegment ClipType_Intersection$address() {
        return ClipType_Intersection.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int ClipType_Intersection()
     * }
     */
    public static int ClipType_Intersection() {
        var mh$ = ClipType_Intersection.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ClipType_Intersection");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ClipType_Union {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ClipType_Union");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int ClipType_Union()
     * }
     */
    public static FunctionDescriptor ClipType_Union$descriptor() {
        return ClipType_Union.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int ClipType_Union()
     * }
     */
    public static MethodHandle ClipType_Union$handle() {
        return ClipType_Union.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int ClipType_Union()
     * }
     */
    public static MemorySegment ClipType_Union$address() {
        return ClipType_Union.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int ClipType_Union()
     * }
     */
    public static int ClipType_Union() {
        var mh$ = ClipType_Union.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ClipType_Union");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ClipType_Difference {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ClipType_Difference");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int ClipType_Difference()
     * }
     */
    public static FunctionDescriptor ClipType_Difference$descriptor() {
        return ClipType_Difference.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int ClipType_Difference()
     * }
     */
    public static MethodHandle ClipType_Difference$handle() {
        return ClipType_Difference.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int ClipType_Difference()
     * }
     */
    public static MemorySegment ClipType_Difference$address() {
        return ClipType_Difference.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int ClipType_Difference()
     * }
     */
    public static int ClipType_Difference() {
        var mh$ = ClipType_Difference.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ClipType_Difference");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ClipType_Xor {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ClipType_Xor");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int ClipType_Xor()
     * }
     */
    public static FunctionDescriptor ClipType_Xor$descriptor() {
        return ClipType_Xor.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int ClipType_Xor()
     * }
     */
    public static MethodHandle ClipType_Xor$handle() {
        return ClipType_Xor.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int ClipType_Xor()
     * }
     */
    public static MemorySegment ClipType_Xor$address() {
        return ClipType_Xor.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int ClipType_Xor()
     * }
     */
    public static int ClipType_Xor() {
        var mh$ = ClipType_Xor.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ClipType_Xor");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class FillRule_EvenOdd {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("FillRule_EvenOdd");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int FillRule_EvenOdd()
     * }
     */
    public static FunctionDescriptor FillRule_EvenOdd$descriptor() {
        return FillRule_EvenOdd.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int FillRule_EvenOdd()
     * }
     */
    public static MethodHandle FillRule_EvenOdd$handle() {
        return FillRule_EvenOdd.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int FillRule_EvenOdd()
     * }
     */
    public static MemorySegment FillRule_EvenOdd$address() {
        return FillRule_EvenOdd.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int FillRule_EvenOdd()
     * }
     */
    public static int FillRule_EvenOdd() {
        var mh$ = FillRule_EvenOdd.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("FillRule_EvenOdd");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class FillRule_NonZero {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("FillRule_NonZero");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int FillRule_NonZero()
     * }
     */
    public static FunctionDescriptor FillRule_NonZero$descriptor() {
        return FillRule_NonZero.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int FillRule_NonZero()
     * }
     */
    public static MethodHandle FillRule_NonZero$handle() {
        return FillRule_NonZero.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int FillRule_NonZero()
     * }
     */
    public static MemorySegment FillRule_NonZero$address() {
        return FillRule_NonZero.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int FillRule_NonZero()
     * }
     */
    public static int FillRule_NonZero() {
        var mh$ = FillRule_NonZero.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("FillRule_NonZero");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class FillRule_Positive {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("FillRule_Positive");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int FillRule_Positive()
     * }
     */
    public static FunctionDescriptor FillRule_Positive$descriptor() {
        return FillRule_Positive.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int FillRule_Positive()
     * }
     */
    public static MethodHandle FillRule_Positive$handle() {
        return FillRule_Positive.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int FillRule_Positive()
     * }
     */
    public static MemorySegment FillRule_Positive$address() {
        return FillRule_Positive.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int FillRule_Positive()
     * }
     */
    public static int FillRule_Positive() {
        var mh$ = FillRule_Positive.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("FillRule_Positive");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class FillRule_Negative {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("FillRule_Negative");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int FillRule_Negative()
     * }
     */
    public static FunctionDescriptor FillRule_Negative$descriptor() {
        return FillRule_Negative.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int FillRule_Negative()
     * }
     */
    public static MethodHandle FillRule_Negative$handle() {
        return FillRule_Negative.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int FillRule_Negative()
     * }
     */
    public static MemorySegment FillRule_Negative$address() {
        return FillRule_Negative.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int FillRule_Negative()
     * }
     */
    public static int FillRule_Negative() {
        var mh$ = FillRule_Negative.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("FillRule_Negative");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class JoinType_Square {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("JoinType_Square");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int JoinType_Square()
     * }
     */
    public static FunctionDescriptor JoinType_Square$descriptor() {
        return JoinType_Square.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int JoinType_Square()
     * }
     */
    public static MethodHandle JoinType_Square$handle() {
        return JoinType_Square.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int JoinType_Square()
     * }
     */
    public static MemorySegment JoinType_Square$address() {
        return JoinType_Square.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int JoinType_Square()
     * }
     */
    public static int JoinType_Square() {
        var mh$ = JoinType_Square.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("JoinType_Square");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class JoinType_Bevel {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("JoinType_Bevel");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int JoinType_Bevel()
     * }
     */
    public static FunctionDescriptor JoinType_Bevel$descriptor() {
        return JoinType_Bevel.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int JoinType_Bevel()
     * }
     */
    public static MethodHandle JoinType_Bevel$handle() {
        return JoinType_Bevel.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int JoinType_Bevel()
     * }
     */
    public static MemorySegment JoinType_Bevel$address() {
        return JoinType_Bevel.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int JoinType_Bevel()
     * }
     */
    public static int JoinType_Bevel() {
        var mh$ = JoinType_Bevel.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("JoinType_Bevel");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class JoinType_Round {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("JoinType_Round");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int JoinType_Round()
     * }
     */
    public static FunctionDescriptor JoinType_Round$descriptor() {
        return JoinType_Round.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int JoinType_Round()
     * }
     */
    public static MethodHandle JoinType_Round$handle() {
        return JoinType_Round.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int JoinType_Round()
     * }
     */
    public static MemorySegment JoinType_Round$address() {
        return JoinType_Round.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int JoinType_Round()
     * }
     */
    public static int JoinType_Round() {
        var mh$ = JoinType_Round.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("JoinType_Round");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class JoinType_Miter {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("JoinType_Miter");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int JoinType_Miter()
     * }
     */
    public static FunctionDescriptor JoinType_Miter$descriptor() {
        return JoinType_Miter.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int JoinType_Miter()
     * }
     */
    public static MethodHandle JoinType_Miter$handle() {
        return JoinType_Miter.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int JoinType_Miter()
     * }
     */
    public static MemorySegment JoinType_Miter$address() {
        return JoinType_Miter.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int JoinType_Miter()
     * }
     */
    public static int JoinType_Miter() {
        var mh$ = JoinType_Miter.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("JoinType_Miter");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EndType_Polygon {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EndType_Polygon");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int EndType_Polygon()
     * }
     */
    public static FunctionDescriptor EndType_Polygon$descriptor() {
        return EndType_Polygon.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int EndType_Polygon()
     * }
     */
    public static MethodHandle EndType_Polygon$handle() {
        return EndType_Polygon.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int EndType_Polygon()
     * }
     */
    public static MemorySegment EndType_Polygon$address() {
        return EndType_Polygon.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int EndType_Polygon()
     * }
     */
    public static int EndType_Polygon() {
        var mh$ = EndType_Polygon.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EndType_Polygon");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EndType_Joined {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EndType_Joined");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int EndType_Joined()
     * }
     */
    public static FunctionDescriptor EndType_Joined$descriptor() {
        return EndType_Joined.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int EndType_Joined()
     * }
     */
    public static MethodHandle EndType_Joined$handle() {
        return EndType_Joined.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int EndType_Joined()
     * }
     */
    public static MemorySegment EndType_Joined$address() {
        return EndType_Joined.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int EndType_Joined()
     * }
     */
    public static int EndType_Joined() {
        var mh$ = EndType_Joined.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EndType_Joined");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EndType_Butt {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EndType_Butt");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int EndType_Butt()
     * }
     */
    public static FunctionDescriptor EndType_Butt$descriptor() {
        return EndType_Butt.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int EndType_Butt()
     * }
     */
    public static MethodHandle EndType_Butt$handle() {
        return EndType_Butt.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int EndType_Butt()
     * }
     */
    public static MemorySegment EndType_Butt$address() {
        return EndType_Butt.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int EndType_Butt()
     * }
     */
    public static int EndType_Butt() {
        var mh$ = EndType_Butt.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EndType_Butt");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EndType_Square {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EndType_Square");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int EndType_Square()
     * }
     */
    public static FunctionDescriptor EndType_Square$descriptor() {
        return EndType_Square.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int EndType_Square()
     * }
     */
    public static MethodHandle EndType_Square$handle() {
        return EndType_Square.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int EndType_Square()
     * }
     */
    public static MemorySegment EndType_Square$address() {
        return EndType_Square.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int EndType_Square()
     * }
     */
    public static int EndType_Square() {
        var mh$ = EndType_Square.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EndType_Square");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class EndType_Round {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("EndType_Round");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int EndType_Round()
     * }
     */
    public static FunctionDescriptor EndType_Round$descriptor() {
        return EndType_Round.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int EndType_Round()
     * }
     */
    public static MethodHandle EndType_Round$handle() {
        return EndType_Round.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int EndType_Round()
     * }
     */
    public static MemorySegment EndType_Round$address() {
        return EndType_Round.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int EndType_Round()
     * }
     */
    public static int EndType_Round() {
        var mh$ = EndType_Round.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("EndType_Round");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Paths64_New {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Paths64_New");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * Paths64 *Paths64_New()
     * }
     */
    public static FunctionDescriptor Paths64_New$descriptor() {
        return Paths64_New.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * Paths64 *Paths64_New()
     * }
     */
    public static MethodHandle Paths64_New$handle() {
        return Paths64_New.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * Paths64 *Paths64_New()
     * }
     */
    public static MemorySegment Paths64_New$address() {
        return Paths64_New.ADDR;
    }

    /**
     * {@snippet lang=c :
     * Paths64 *Paths64_New()
     * }
     */
    public static MemorySegment Paths64_New() {
        var mh$ = Paths64_New.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Paths64_New");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Paths64_delete {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            clippercapi_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Paths64_delete");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void Paths64_delete(Paths64 *paths)
     * }
     */
    public static FunctionDescriptor Paths64_delete$descriptor() {
        return Paths64_delete.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void Paths64_delete(Paths64 *paths)
     * }
     */
    public static MethodHandle Paths64_delete$handle() {
        return Paths64_delete.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void Paths64_delete(Paths64 *paths)
     * }
     */
    public static MemorySegment Paths64_delete$address() {
        return Paths64_delete.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void Paths64_delete(Paths64 *paths)
     * }
     */
    public static void Paths64_delete(MemorySegment paths) {
        var mh$ = Paths64_delete.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Paths64_delete", paths);
            }
            mh$.invokeExact(paths);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Paths64_pathCount {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT,
            clippercapi_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Paths64_pathCount");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int Paths64_pathCount(Paths64 *paths)
     * }
     */
    public static FunctionDescriptor Paths64_pathCount$descriptor() {
        return Paths64_pathCount.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int Paths64_pathCount(Paths64 *paths)
     * }
     */
    public static MethodHandle Paths64_pathCount$handle() {
        return Paths64_pathCount.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int Paths64_pathCount(Paths64 *paths)
     * }
     */
    public static MemorySegment Paths64_pathCount$address() {
        return Paths64_pathCount.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int Paths64_pathCount(Paths64 *paths)
     * }
     */
    public static int Paths64_pathCount(MemorySegment paths) {
        var mh$ = Paths64_pathCount.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Paths64_pathCount", paths);
            }
            return (int)mh$.invokeExact(paths);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Paths64_pathPointCount {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_INT,
            clippercapi_h.C_POINTER,
            clippercapi_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Paths64_pathPointCount");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int Paths64_pathPointCount(Paths64 *paths, int pathIndex)
     * }
     */
    public static FunctionDescriptor Paths64_pathPointCount$descriptor() {
        return Paths64_pathPointCount.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int Paths64_pathPointCount(Paths64 *paths, int pathIndex)
     * }
     */
    public static MethodHandle Paths64_pathPointCount$handle() {
        return Paths64_pathPointCount.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int Paths64_pathPointCount(Paths64 *paths, int pathIndex)
     * }
     */
    public static MemorySegment Paths64_pathPointCount$address() {
        return Paths64_pathPointCount.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int Paths64_pathPointCount(Paths64 *paths, int pathIndex)
     * }
     */
    public static int Paths64_pathPointCount(MemorySegment paths, int pathIndex) {
        var mh$ = Paths64_pathPointCount.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Paths64_pathPointCount", paths, pathIndex);
            }
            return (int)mh$.invokeExact(paths, pathIndex);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Paths64_pathPoints {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_POINTER,
            clippercapi_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Paths64_pathPoints");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * long long *Paths64_pathPoints(Paths64 *paths, int pathIndex)
     * }
     */
    public static FunctionDescriptor Paths64_pathPoints$descriptor() {
        return Paths64_pathPoints.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * long long *Paths64_pathPoints(Paths64 *paths, int pathIndex)
     * }
     */
    public static MethodHandle Paths64_pathPoints$handle() {
        return Paths64_pathPoints.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * long long *Paths64_pathPoints(Paths64 *paths, int pathIndex)
     * }
     */
    public static MemorySegment Paths64_pathPoints$address() {
        return Paths64_pathPoints.ADDR;
    }

    /**
     * {@snippet lang=c :
     * long long *Paths64_pathPoints(Paths64 *paths, int pathIndex)
     * }
     */
    public static MemorySegment Paths64_pathPoints(MemorySegment paths, int pathIndex) {
        var mh$ = Paths64_pathPoints.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Paths64_pathPoints", paths, pathIndex);
            }
            return (MemorySegment)mh$.invokeExact(paths, pathIndex);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Paths64_addPath {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_POINTER,
            clippercapi_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Paths64_addPath");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void Paths64_addPath(Paths64 *paths, long long *points, int pointCount)
     * }
     */
    public static FunctionDescriptor Paths64_addPath$descriptor() {
        return Paths64_addPath.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void Paths64_addPath(Paths64 *paths, long long *points, int pointCount)
     * }
     */
    public static MethodHandle Paths64_addPath$handle() {
        return Paths64_addPath.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void Paths64_addPath(Paths64 *paths, long long *points, int pointCount)
     * }
     */
    public static MemorySegment Paths64_addPath$address() {
        return Paths64_addPath.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void Paths64_addPath(Paths64 *paths, long long *points, int pointCount)
     * }
     */
    public static void Paths64_addPath(MemorySegment paths, MemorySegment points, int pointCount) {
        var mh$ = Paths64_addPath.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Paths64_addPath", paths, points, pointCount);
            }
            mh$.invokeExact(paths, points, pointCount);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Paths64_addPaths64 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Paths64_addPaths64");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void Paths64_addPaths64(Paths64 *paths, Paths64 *other)
     * }
     */
    public static FunctionDescriptor Paths64_addPaths64$descriptor() {
        return Paths64_addPaths64.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void Paths64_addPaths64(Paths64 *paths, Paths64 *other)
     * }
     */
    public static MethodHandle Paths64_addPaths64$handle() {
        return Paths64_addPaths64.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void Paths64_addPaths64(Paths64 *paths, Paths64 *other)
     * }
     */
    public static MemorySegment Paths64_addPaths64$address() {
        return Paths64_addPaths64.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void Paths64_addPaths64(Paths64 *paths, Paths64 *other)
     * }
     */
    public static void Paths64_addPaths64(MemorySegment paths, MemorySegment other) {
        var mh$ = Paths64_addPaths64.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Paths64_addPaths64", paths, other);
            }
            mh$.invokeExact(paths, other);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Clipper_Translate {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Clipper_Translate");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void Clipper_Translate(Paths64 *inPaths, long long tx, long long ty, Paths64 *outPaths)
     * }
     */
    public static FunctionDescriptor Clipper_Translate$descriptor() {
        return Clipper_Translate.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void Clipper_Translate(Paths64 *inPaths, long long tx, long long ty, Paths64 *outPaths)
     * }
     */
    public static MethodHandle Clipper_Translate$handle() {
        return Clipper_Translate.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void Clipper_Translate(Paths64 *inPaths, long long tx, long long ty, Paths64 *outPaths)
     * }
     */
    public static MemorySegment Clipper_Translate$address() {
        return Clipper_Translate.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void Clipper_Translate(Paths64 *inPaths, long long tx, long long ty, Paths64 *outPaths)
     * }
     */
    public static void Clipper_Translate(MemorySegment inPaths, long tx, long ty, MemorySegment outPaths) {
        var mh$ = Clipper_Translate.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Clipper_Translate", inPaths, tx, ty, outPaths);
            }
            mh$.invokeExact(inPaths, tx, ty, outPaths);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Clipper_Transform {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_INT,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Clipper_Transform");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void Clipper_Transform(Paths64 *inPaths, int shift, long long m00, long long m10, long long m01, long long m11, long long m02, long long m12, Paths64 *outPaths)
     * }
     */
    public static FunctionDescriptor Clipper_Transform$descriptor() {
        return Clipper_Transform.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void Clipper_Transform(Paths64 *inPaths, int shift, long long m00, long long m10, long long m01, long long m11, long long m02, long long m12, Paths64 *outPaths)
     * }
     */
    public static MethodHandle Clipper_Transform$handle() {
        return Clipper_Transform.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void Clipper_Transform(Paths64 *inPaths, int shift, long long m00, long long m10, long long m01, long long m11, long long m02, long long m12, Paths64 *outPaths)
     * }
     */
    public static MemorySegment Clipper_Transform$address() {
        return Clipper_Transform.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void Clipper_Transform(Paths64 *inPaths, int shift, long long m00, long long m10, long long m01, long long m11, long long m02, long long m12, Paths64 *outPaths)
     * }
     */
    public static void Clipper_Transform(MemorySegment inPaths, int shift, long m00, long m10, long m01, long m11, long m02, long m12, MemorySegment outPaths) {
        var mh$ = Clipper_Transform.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Clipper_Transform", inPaths, shift, m00, m10, m01, m11, m02, m12, outPaths);
            }
            mh$.invokeExact(inPaths, shift, m00, m10, m01, m11, m02, m12, outPaths);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Clipper_BooleanOp {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_POINTER,
            clippercapi_h.C_POINTER,
            clippercapi_h.C_INT,
            clippercapi_h.C_INT,
            clippercapi_h.C_BOOL,
            clippercapi_h.C_BOOL,
            clippercapi_h.C_POINTER,
            clippercapi_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Clipper_BooleanOp");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void Clipper_BooleanOp(Paths64 *inClosedSubjectPaths, Paths64 *inOpenSubjectPaths, Paths64 *inClipPaths, int clipType, int fillRule, _Bool preserveCollinear, _Bool reverseSolution, Paths64 *outClosedPaths, Paths64 *outOpenPaths)
     * }
     */
    public static FunctionDescriptor Clipper_BooleanOp$descriptor() {
        return Clipper_BooleanOp.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void Clipper_BooleanOp(Paths64 *inClosedSubjectPaths, Paths64 *inOpenSubjectPaths, Paths64 *inClipPaths, int clipType, int fillRule, _Bool preserveCollinear, _Bool reverseSolution, Paths64 *outClosedPaths, Paths64 *outOpenPaths)
     * }
     */
    public static MethodHandle Clipper_BooleanOp$handle() {
        return Clipper_BooleanOp.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void Clipper_BooleanOp(Paths64 *inClosedSubjectPaths, Paths64 *inOpenSubjectPaths, Paths64 *inClipPaths, int clipType, int fillRule, _Bool preserveCollinear, _Bool reverseSolution, Paths64 *outClosedPaths, Paths64 *outOpenPaths)
     * }
     */
    public static MemorySegment Clipper_BooleanOp$address() {
        return Clipper_BooleanOp.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void Clipper_BooleanOp(Paths64 *inClosedSubjectPaths, Paths64 *inOpenSubjectPaths, Paths64 *inClipPaths, int clipType, int fillRule, _Bool preserveCollinear, _Bool reverseSolution, Paths64 *outClosedPaths, Paths64 *outOpenPaths)
     * }
     */
    public static void Clipper_BooleanOp(MemorySegment inClosedSubjectPaths, MemorySegment inOpenSubjectPaths, MemorySegment inClipPaths, int clipType, int fillRule, boolean preserveCollinear, boolean reverseSolution, MemorySegment outClosedPaths, MemorySegment outOpenPaths) {
        var mh$ = Clipper_BooleanOp.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Clipper_BooleanOp", inClosedSubjectPaths, inOpenSubjectPaths, inClipPaths, clipType, fillRule, preserveCollinear, reverseSolution, outClosedPaths, outOpenPaths);
            }
            mh$.invokeExact(inClosedSubjectPaths, inOpenSubjectPaths, inClipPaths, clipType, fillRule, preserveCollinear, reverseSolution, outClosedPaths, outOpenPaths);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Clipper_Offset {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_DOUBLE,
            clippercapi_h.C_INT,
            clippercapi_h.C_INT,
            clippercapi_h.C_DOUBLE,
            clippercapi_h.C_DOUBLE,
            clippercapi_h.C_BOOL,
            clippercapi_h.C_BOOL,
            clippercapi_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Clipper_Offset");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void Clipper_Offset(Paths64 *inPaths, double delta, int joinType, int endType, double miterLimit, double arcTolerance, _Bool preserveCollinear, _Bool reverseSolution, Paths64 *outPaths)
     * }
     */
    public static FunctionDescriptor Clipper_Offset$descriptor() {
        return Clipper_Offset.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void Clipper_Offset(Paths64 *inPaths, double delta, int joinType, int endType, double miterLimit, double arcTolerance, _Bool preserveCollinear, _Bool reverseSolution, Paths64 *outPaths)
     * }
     */
    public static MethodHandle Clipper_Offset$handle() {
        return Clipper_Offset.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void Clipper_Offset(Paths64 *inPaths, double delta, int joinType, int endType, double miterLimit, double arcTolerance, _Bool preserveCollinear, _Bool reverseSolution, Paths64 *outPaths)
     * }
     */
    public static MemorySegment Clipper_Offset$address() {
        return Clipper_Offset.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void Clipper_Offset(Paths64 *inPaths, double delta, int joinType, int endType, double miterLimit, double arcTolerance, _Bool preserveCollinear, _Bool reverseSolution, Paths64 *outPaths)
     * }
     */
    public static void Clipper_Offset(MemorySegment inPaths, double delta, int joinType, int endType, double miterLimit, double arcTolerance, boolean preserveCollinear, boolean reverseSolution, MemorySegment outPaths) {
        var mh$ = Clipper_Offset.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Clipper_Offset", inPaths, delta, joinType, endType, miterLimit, arcTolerance, preserveCollinear, reverseSolution, outPaths);
            }
            mh$.invokeExact(inPaths, delta, joinType, endType, miterLimit, arcTolerance, preserveCollinear, reverseSolution, outPaths);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Clipper_IntersectClosedWithRect {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_POINTER,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Clipper_IntersectClosedWithRect");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * Paths64 *Clipper_IntersectClosedWithRect(Paths64 *paths, long long left, long long top, long long right, long long bottom)
     * }
     */
    public static FunctionDescriptor Clipper_IntersectClosedWithRect$descriptor() {
        return Clipper_IntersectClosedWithRect.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * Paths64 *Clipper_IntersectClosedWithRect(Paths64 *paths, long long left, long long top, long long right, long long bottom)
     * }
     */
    public static MethodHandle Clipper_IntersectClosedWithRect$handle() {
        return Clipper_IntersectClosedWithRect.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * Paths64 *Clipper_IntersectClosedWithRect(Paths64 *paths, long long left, long long top, long long right, long long bottom)
     * }
     */
    public static MemorySegment Clipper_IntersectClosedWithRect$address() {
        return Clipper_IntersectClosedWithRect.ADDR;
    }

    /**
     * {@snippet lang=c :
     * Paths64 *Clipper_IntersectClosedWithRect(Paths64 *paths, long long left, long long top, long long right, long long bottom)
     * }
     */
    public static MemorySegment Clipper_IntersectClosedWithRect(MemorySegment paths, long left, long top, long right, long bottom) {
        var mh$ = Clipper_IntersectClosedWithRect.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Clipper_IntersectClosedWithRect", paths, left, top, right, bottom);
            }
            return (MemorySegment)mh$.invokeExact(paths, left, top, right, bottom);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Clipper_IntersectOpenWithRect {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_POINTER,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG,
            clippercapi_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Clipper_IntersectOpenWithRect");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * Paths64 *Clipper_IntersectOpenWithRect(Paths64 *paths, long long left, long long top, long long right, long long bottom)
     * }
     */
    public static FunctionDescriptor Clipper_IntersectOpenWithRect$descriptor() {
        return Clipper_IntersectOpenWithRect.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * Paths64 *Clipper_IntersectOpenWithRect(Paths64 *paths, long long left, long long top, long long right, long long bottom)
     * }
     */
    public static MethodHandle Clipper_IntersectOpenWithRect$handle() {
        return Clipper_IntersectOpenWithRect.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * Paths64 *Clipper_IntersectOpenWithRect(Paths64 *paths, long long left, long long top, long long right, long long bottom)
     * }
     */
    public static MemorySegment Clipper_IntersectOpenWithRect$address() {
        return Clipper_IntersectOpenWithRect.ADDR;
    }

    /**
     * {@snippet lang=c :
     * Paths64 *Clipper_IntersectOpenWithRect(Paths64 *paths, long long left, long long top, long long right, long long bottom)
     * }
     */
    public static MemorySegment Clipper_IntersectOpenWithRect(MemorySegment paths, long left, long top, long right, long bottom) {
        var mh$ = Clipper_IntersectOpenWithRect.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Clipper_IntersectOpenWithRect", paths, left, top, right, bottom);
            }
            return (MemorySegment)mh$.invokeExact(paths, left, top, right, bottom);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class Clipper_Simplify {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            clippercapi_h.C_POINTER,
            clippercapi_h.C_POINTER,
            clippercapi_h.C_DOUBLE,
            clippercapi_h.C_BOOL
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Clipper_Simplify");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * Paths64 *Clipper_Simplify(Paths64 *paths, double epsilon, _Bool isClosed)
     * }
     */
    public static FunctionDescriptor Clipper_Simplify$descriptor() {
        return Clipper_Simplify.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * Paths64 *Clipper_Simplify(Paths64 *paths, double epsilon, _Bool isClosed)
     * }
     */
    public static MethodHandle Clipper_Simplify$handle() {
        return Clipper_Simplify.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * Paths64 *Clipper_Simplify(Paths64 *paths, double epsilon, _Bool isClosed)
     * }
     */
    public static MemorySegment Clipper_Simplify$address() {
        return Clipper_Simplify.ADDR;
    }

    /**
     * {@snippet lang=c :
     * Paths64 *Clipper_Simplify(Paths64 *paths, double epsilon, _Bool isClosed)
     * }
     */
    public static MemorySegment Clipper_Simplify(MemorySegment paths, double epsilon, boolean isClosed) {
        var mh$ = Clipper_Simplify.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Clipper_Simplify", paths, epsilon, isClosed);
            }
            return (MemorySegment)mh$.invokeExact(paths, epsilon, isClosed);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

